#!/usr/bin/env bash
#resolve localhost to 127.0.0.2 and fb to 8.8.8.8
sudo sed -i 's/^127\.0\.0\.1.*localhost/127.0.0.2 localhost/' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null

